../../sim/tb_debug.sv
../../rtl/*.sv
../../rtl/Bus/*.sv
../../rtl/Common/*.sv
../../rtl/Common/Clock/*.sv
../../rtl/Core/*.sv
../../rtl/Core/Mul_Div/*.sv
../../rtl/Debug/*.sv
../../rtl/Periph/*.sv
../../rtl/Periph/plic/*.sv
../../rtl/Periph/uart/*.sv
../../rtl/Periph/timer/*.sv
