onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_apb_plic/irq_i
add wave -noupdate /tb_apb_plic/irq_o
add wave -noupdate /tb_apb_plic/errors
add wave -noupdate /tb_apb_plic/test_count
add wave -noupdate /tb_apb_plic/reset_watchdog
add wave -noupdate /tb_apb_plic/got_reset
add wave -noupdate /tb_apb_plic/dut/PCLK
add wave -noupdate /tb_apb_plic/dut/PRESETn
add wave -noupdate /tb_apb_plic/dut/PADDR
add wave -noupdate /tb_apb_plic/dut/PSEL
add wave -noupdate /tb_apb_plic/dut/PENABLE
add wave -noupdate /tb_apb_plic/dut/PWRITE
add wave -noupdate /tb_apb_plic/dut/PSTRB
add wave -noupdate /tb_apb_plic/dut/PWDATA
add wave -noupdate /tb_apb_plic/dut/PRDATA
add wave -noupdate /tb_apb_plic/dut/PREADY
add wave -noupdate /tb_apb_plic/dut/PSLVERR
add wave -noupdate /tb_apb_plic/dut/irq_i
add wave -noupdate /tb_apb_plic/dut/irq_o
add wave -noupdate /tb_apb_plic/dut/is_prio
add wave -noupdate /tb_apb_plic/dut/is_pending
add wave -noupdate /tb_apb_plic/dut/is_target_enable
add wave -noupdate /tb_apb_plic/dut/is_target_threshold
add wave -noupdate /tb_apb_plic/dut/is_target_claim
add wave -noupdate /tb_apb_plic/dut/src_idx
add wave -noupdate /tb_apb_plic/dut/word_idx
add wave -noupdate /tb_apb_plic/dut/tgt_idx
add wave -noupdate /tb_apb_plic/dut/pending_bits
add wave -noupdate /tb_apb_plic/dut/irq_synced
add wave -noupdate /tb_apb_plic/dut/gateway_claim
add wave -noupdate /tb_apb_plic/dut/gateway_complete
add wave -noupdate /tb_apb_plic/dut/ct_input_data
add wave -noupdate /tb_apb_plic/dut/ct_max_prio
add wave -noupdate /tb_apb_plic/dut/ct_max_idx
add wave -noupdate /tb_apb_plic/dut/winner_idx
add wave -noupdate /tb_apb_plic/dut/winner_prio
add wave -noupdate /tb_apb_plic/dut/irq_valid
add wave -noupdate /tb_apb_plic/dut/target_claim_read
add wave -noupdate /tb_apb_plic/dut/target_complete_write
add wave -noupdate /tb_apb_plic/dut/target_complete_id
add wave -noupdate /tb_apb_plic/dut/target_claimed_id
add wave -noupdate /tb_apb_plic/dut/target_eip
add wave -noupdate /tb_apb_plic/dut/target_claim_vec
add wave -noupdate /tb_apb_plic/dut/target_complete_vec
add wave -noupdate /tb_apb_plic/dut/wr_en
add wave -noupdate /tb_apb_plic/dut/rd_en
add wave -noupdate /tb_apb_plic/dut/enable_bits
add wave -noupdate /tb_apb_plic/dut/prio_regs
add wave -noupdate /tb_apb_plic/dut/threshold_q
add wave -noupdate /tb_apb_plic/dut/u_sync/dst_clk
add wave -noupdate /tb_apb_plic/dut/u_sync/dst_rst_n
add wave -noupdate /tb_apb_plic/dut/u_sync/async_sig
add wave -noupdate /tb_apb_plic/dut/u_sync/sync_sig
add wave -noupdate {/tb_apb_plic/dut/gen_gateway[3]/u_gateway/clk}
add wave -noupdate {/tb_apb_plic/dut/gen_gateway[3]/u_gateway/rst_n}
add wave -noupdate {/tb_apb_plic/dut/gen_gateway[3]/u_gateway/irq_source}
add wave -noupdate {/tb_apb_plic/dut/gen_gateway[3]/u_gateway/claim}
add wave -noupdate {/tb_apb_plic/dut/gen_gateway[3]/u_gateway/complete}
add wave -noupdate {/tb_apb_plic/dut/gen_gateway[3]/u_gateway/pending}
add wave -noupdate {/tb_apb_plic/dut/gen_gateway[3]/u_gateway/gateway_open}
add wave -noupdate {/tb_apb_plic/dut/gen_target[0]/u_target/clk}
add wave -noupdate {/tb_apb_plic/dut/gen_target[0]/u_target/rst_n}
add wave -noupdate {/tb_apb_plic/dut/gen_target[0]/u_target/max_id}
add wave -noupdate {/tb_apb_plic/dut/gen_target[0]/u_target/max_prio}
add wave -noupdate {/tb_apb_plic/dut/gen_target[0]/u_target/irq_valid}
add wave -noupdate {/tb_apb_plic/dut/gen_target[0]/u_target/claim_read}
add wave -noupdate {/tb_apb_plic/dut/gen_target[0]/u_target/complete_write}
add wave -noupdate {/tb_apb_plic/dut/gen_target[0]/u_target/complete_id}
add wave -noupdate {/tb_apb_plic/dut/gen_target[0]/u_target/claim_vec}
add wave -noupdate {/tb_apb_plic/dut/gen_target[0]/u_target/complete_vec}
add wave -noupdate {/tb_apb_plic/dut/gen_target[0]/u_target/claimed_id}
add wave -noupdate {/tb_apb_plic/dut/gen_target[0]/u_target/eip}
add wave -noupdate {/tb_apb_plic/dut/gen_target[0]/u_target/state}
add wave -noupdate {/tb_apb_plic/dut/gen_target[0]/u_target/state_next}
add wave -noupdate {/tb_apb_plic/dut/gen_target[0]/u_target/in_service_id}
add wave -noupdate {/tb_apb_plic/dut/gen_target[0]/u_target/in_service_id_next}
add wave -noupdate /tb_apb_plic/check/actual
add wave -noupdate /tb_apb_plic/check/expected
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {2758406 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 353
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {573725 ps}
