../../sim/tb_soc_top.sv
../../rtl/*.sv
../../rtl/Bus/*.sv
../../rtl/Common/*.sv
../../rtl/Common/Clock/*.sv
../../rtl/Core/*.sv
../../rtl/Core/Mul_Div/*.sv
../../rtl/Periph/*.sv
../../rtl/Periph/uart/*.sv