onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_soc_top/clk
add wave -noupdate /tb_soc_top/rst_n
add wave -noupdate /tb_soc_top/download_en
add wave -noupdate -expand /tb_soc_top/gpio_io
add wave -noupdate /tb_soc_top/uart_rx
add wave -noupdate /tb_soc_top/uart_tx
add wave -noupdate /tb_soc_top/download_done
add wave -noupdate /tb_soc_top/timer_channel_io
add wave -noupdate /tb_soc_top/inst_cnt
add wave -noupdate /tb_soc_top/tx_data_valid
add wave -noupdate /tb_soc_top/tx_data_valid_d
add wave -noupdate /tb_soc_top/uart_tx_complete
add wave -noupdate /tb_soc_top/lsr6_d
add wave -noupdate /tb_soc_top/prev_pwm
add wave -noupdate /tb_soc_top/pwm_ch
add wave -noupdate /tb_soc_top/u_SoC_top/sys_clk
add wave -noupdate /tb_soc_top/u_SoC_top/sys_rst_n
add wave -noupdate /tb_soc_top/u_SoC_top/uart_rx
add wave -noupdate /tb_soc_top/u_SoC_top/uart_tx
add wave -noupdate /tb_soc_top/u_SoC_top/gpio_io
add wave -noupdate /tb_soc_top/u_SoC_top/timer_channel_io
add wave -noupdate /tb_soc_top/u_SoC_top/rst_n_sync
add wave -noupdate /tb_soc_top/u_SoC_top/itcm_wr_en
add wave -noupdate /tb_soc_top/u_SoC_top/itcm_wr_addr
add wave -noupdate /tb_soc_top/u_SoC_top/itcm_wr_data
add wave -noupdate /tb_soc_top/u_SoC_top/dtcm_wr_en
add wave -noupdate /tb_soc_top/u_SoC_top/dtcm_wr_addr
add wave -noupdate /tb_soc_top/u_SoC_top/dtcm_wr_data
add wave -noupdate /tb_soc_top/u_SoC_top/bus_transfer
add wave -noupdate /tb_soc_top/u_SoC_top/bus_access_addr
add wave -noupdate /tb_soc_top/u_SoC_top/bus_access_write
add wave -noupdate /tb_soc_top/u_SoC_top/bus_access_wdata
add wave -noupdate /tb_soc_top/u_SoC_top/bus_access_wstrb
add wave -noupdate /tb_soc_top/u_SoC_top/bus_rdata
add wave -noupdate /tb_soc_top/u_SoC_top/bus_tran_done
add wave -noupdate /tb_soc_top/u_SoC_top/mtime_shadow
add wave -noupdate /tb_soc_top/u_SoC_top/software_int
add wave -noupdate /tb_soc_top/u_SoC_top/timer_int
add wave -noupdate /tb_soc_top/u_SoC_top/external_int
add wave -noupdate /tb_soc_top/u_SoC_top/plic_irq
add wave -noupdate /tb_soc_top/u_SoC_top/axi_awid
add wave -noupdate /tb_soc_top/u_SoC_top/axi_awaddr
add wave -noupdate /tb_soc_top/u_SoC_top/axi_awlen
add wave -noupdate /tb_soc_top/u_SoC_top/axi_awsize
add wave -noupdate /tb_soc_top/u_SoC_top/axi_awburst
add wave -noupdate /tb_soc_top/u_SoC_top/axi_awlock
add wave -noupdate /tb_soc_top/u_SoC_top/axi_awcache
add wave -noupdate /tb_soc_top/u_SoC_top/axi_awprot
add wave -noupdate /tb_soc_top/u_SoC_top/axi_awqos
add wave -noupdate /tb_soc_top/u_SoC_top/axi_awregion
add wave -noupdate /tb_soc_top/u_SoC_top/axi_awvalid
add wave -noupdate /tb_soc_top/u_SoC_top/axi_awready
add wave -noupdate /tb_soc_top/u_SoC_top/axi_wdata
add wave -noupdate /tb_soc_top/u_SoC_top/axi_wstrb
add wave -noupdate /tb_soc_top/u_SoC_top/axi_wlast
add wave -noupdate /tb_soc_top/u_SoC_top/axi_wvalid
add wave -noupdate /tb_soc_top/u_SoC_top/axi_wready
add wave -noupdate /tb_soc_top/u_SoC_top/axi_bid
add wave -noupdate /tb_soc_top/u_SoC_top/axi_bresp
add wave -noupdate /tb_soc_top/u_SoC_top/axi_bvalid
add wave -noupdate /tb_soc_top/u_SoC_top/axi_bready
add wave -noupdate /tb_soc_top/u_SoC_top/axi_arid
add wave -noupdate /tb_soc_top/u_SoC_top/axi_araddr
add wave -noupdate /tb_soc_top/u_SoC_top/axi_arlen
add wave -noupdate /tb_soc_top/u_SoC_top/axi_arsize
add wave -noupdate /tb_soc_top/u_SoC_top/axi_arburst
add wave -noupdate /tb_soc_top/u_SoC_top/axi_arlock
add wave -noupdate /tb_soc_top/u_SoC_top/axi_arcache
add wave -noupdate /tb_soc_top/u_SoC_top/axi_arprot
add wave -noupdate /tb_soc_top/u_SoC_top/axi_arqos
add wave -noupdate /tb_soc_top/u_SoC_top/axi_arregion
add wave -noupdate /tb_soc_top/u_SoC_top/axi_arvalid
add wave -noupdate /tb_soc_top/u_SoC_top/axi_arready
add wave -noupdate /tb_soc_top/u_SoC_top/axi_rid
add wave -noupdate /tb_soc_top/u_SoC_top/axi_rdata
add wave -noupdate /tb_soc_top/u_SoC_top/axi_rresp
add wave -noupdate /tb_soc_top/u_SoC_top/axi_rlast
add wave -noupdate /tb_soc_top/u_SoC_top/axi_rvalid
add wave -noupdate /tb_soc_top/u_SoC_top/axi_rready
add wave -noupdate /tb_soc_top/u_SoC_top/apb_awid
add wave -noupdate /tb_soc_top/u_SoC_top/apb_arid
add wave -noupdate /tb_soc_top/u_SoC_top/apb_bid
add wave -noupdate /tb_soc_top/u_SoC_top/apb_rid
add wave -noupdate /tb_soc_top/u_SoC_top/apb_awaddr
add wave -noupdate /tb_soc_top/u_SoC_top/apb_araddr
add wave -noupdate /tb_soc_top/u_SoC_top/apb_awlen
add wave -noupdate /tb_soc_top/u_SoC_top/apb_arlen
add wave -noupdate /tb_soc_top/u_SoC_top/apb_awsize
add wave -noupdate /tb_soc_top/u_SoC_top/apb_arsize
add wave -noupdate /tb_soc_top/u_SoC_top/apb_awburst
add wave -noupdate /tb_soc_top/u_SoC_top/apb_arburst
add wave -noupdate /tb_soc_top/u_SoC_top/apb_awlock
add wave -noupdate /tb_soc_top/u_SoC_top/apb_arlock
add wave -noupdate /tb_soc_top/u_SoC_top/apb_awcache
add wave -noupdate /tb_soc_top/u_SoC_top/apb_arcache
add wave -noupdate /tb_soc_top/u_SoC_top/apb_awprot
add wave -noupdate /tb_soc_top/u_SoC_top/apb_arprot
add wave -noupdate /tb_soc_top/u_SoC_top/apb_awqos
add wave -noupdate /tb_soc_top/u_SoC_top/apb_arqos
add wave -noupdate /tb_soc_top/u_SoC_top/apb_awregion
add wave -noupdate /tb_soc_top/u_SoC_top/apb_arregion
add wave -noupdate /tb_soc_top/u_SoC_top/apb_awvalid
add wave -noupdate /tb_soc_top/u_SoC_top/apb_awready
add wave -noupdate /tb_soc_top/u_SoC_top/apb_wdata
add wave -noupdate /tb_soc_top/u_SoC_top/apb_wstrb
add wave -noupdate /tb_soc_top/u_SoC_top/apb_wlast
add wave -noupdate /tb_soc_top/u_SoC_top/apb_wvalid
add wave -noupdate /tb_soc_top/u_SoC_top/apb_wready
add wave -noupdate /tb_soc_top/u_SoC_top/apb_bresp
add wave -noupdate /tb_soc_top/u_SoC_top/apb_bvalid
add wave -noupdate /tb_soc_top/u_SoC_top/apb_bready
add wave -noupdate /tb_soc_top/u_SoC_top/apb_arvalid
add wave -noupdate /tb_soc_top/u_SoC_top/apb_arready
add wave -noupdate /tb_soc_top/u_SoC_top/apb_rdata
add wave -noupdate /tb_soc_top/u_SoC_top/apb_rresp
add wave -noupdate /tb_soc_top/u_SoC_top/apb_rlast
add wave -noupdate /tb_soc_top/u_SoC_top/apb_rvalid
add wave -noupdate /tb_soc_top/u_SoC_top/apb_rready
add wave -noupdate /tb_soc_top/u_SoC_top/apb_paddr
add wave -noupdate /tb_soc_top/u_SoC_top/apb_psel
add wave -noupdate /tb_soc_top/u_SoC_top/apb_penable
add wave -noupdate /tb_soc_top/u_SoC_top/apb_pwrite
add wave -noupdate /tb_soc_top/u_SoC_top/apb_pstrb
add wave -noupdate /tb_soc_top/u_SoC_top/apb_pwdata
add wave -noupdate /tb_soc_top/u_SoC_top/apb_pready
add wave -noupdate /tb_soc_top/u_SoC_top/apb_pslverr
add wave -noupdate /tb_soc_top/u_SoC_top/bridge_psel
add wave -noupdate /tb_soc_top/u_SoC_top/bridge_prdata
add wave -noupdate /tb_soc_top/u_SoC_top/bridge_pready
add wave -noupdate /tb_soc_top/u_SoC_top/bridge_pslverr
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_awid
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_arid
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_bid
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_rid
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_awaddr
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_araddr
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_awlen
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_arlen
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_awsize
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_arsize
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_awburst
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_arburst
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_awlock
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_arlock
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_awcache
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_arcache
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_awprot
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_arprot
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_awqos
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_arqos
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_awregion
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_arregion
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_awvalid
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_awready
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_wdata
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_wstrb
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_wlast
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_wvalid
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_wready
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_bresp
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_bvalid
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_bready
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_arvalid
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_arready
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_rdata
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_rresp
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_rlast
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_rvalid
add wave -noupdate /tb_soc_top/u_SoC_top/mrom_flash_rready
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_awid
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_arid
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_bid
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_rid
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_awaddr
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_araddr
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_awlen
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_arlen
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_awsize
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_arsize
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_awburst
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_arburst
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_awlock
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_arlock
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_awcache
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_arcache
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_awprot
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_arprot
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_awqos
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_arqos
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_awregion
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_arregion
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_awvalid
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_awready
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_wdata
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_wstrb
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_wlast
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_wvalid
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_wready
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_bresp
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_bvalid
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_bready
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_arvalid
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_arready
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_rdata
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_rresp
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_rlast
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_rvalid
add wave -noupdate /tb_soc_top/u_SoC_top/ddr_rready
add wave -noupdate /tb_soc_top/u_SoC_top/uart_irq
add wave -noupdate /tb_soc_top/u_SoC_top/gpio_irq
add wave -noupdate /tb_soc_top/u_SoC_top/timer_irq
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/clk
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/rst_n
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/download_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/uart_rec_byte
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/uart_rx_valid
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/itcm_wr_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/itcm_wr_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/itcm_wr_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/dtcm_wr_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/dtcm_wr_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/dtcm_wr_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/download_done
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/current_state
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/next_state
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/byte_cnt
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/recv_data_q
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/recv_data_n
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/word_count
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/start_frame_det
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/uart_rx_valid_d
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/uart_rx_valid_pos
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/itcm_wr_en_comb
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/dtcm_wr_en_comb
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/itcm_wr_data_comb
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/dtcm_wr_data_comb
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/clk
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/rst_n
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/itcm_wr_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/itcm_wr_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/itcm_wr_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/mtime_shadow
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/software_int
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/timer_int
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/external_int
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/bus_rdata
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/bus_tran_done
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/bus_transfer
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/bus_access_write
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/bus_access_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/bus_access_wstrb
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/bus_access_wdata
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/branch_jump_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/branch_jump_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/trap_jump
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/trap_jump_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/priv_mode
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/load_use_flag
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/mem_access_ready
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/mul_div_ready
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/exception_code_if
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/exception_code_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/exception_code_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/exception_code_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/exception_val_if
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/exception_val_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/exception_val_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/exception_val_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/pc_stall
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/ctrl_jump_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/ctrl_jump_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/if_id_stall
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/if_id_flush
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/id_ex_stall
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/id_ex_flush
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/ex_mem_stall
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/ex_mem_flush
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/mem_wb_stall
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/mem_wb_flush
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/exception_inst_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/exception_trap
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/exception_code
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/exception_val
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/next_inst_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/alu_op1_from_id_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/alu_op2_from_id_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/alu_op1_forward
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/alu_op2_forward
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wr_mem_data_temp
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/rs2_data_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/jump_imm_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/inst_addr_plus_4_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wr_reg_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/rd_rs1_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/rd_rs2_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/rd_rs1_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/rd_rs2_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wr_reg_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wr_reg_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/pc
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/inst_addr_if
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/inst
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/predict_taken_if
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/predict_target_if
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/inst_addr_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/inst_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/predict_taken_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/predict_target_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/alu_op1_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/alu_op2_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/imm_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/jump_imm_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/inst_addr_plus_4_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/access_en_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/access_wr_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wr_reg_en_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/access_csr_en_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/csr_addr_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/inst_addr_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/inst_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/predict_taken_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/predict_target_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/imm_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/access_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/access_wr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/mem_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/rd_mem_func3_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wr_mem_data_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wr_mem_mask_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wr_reg_en_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wr_reg_addr_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wr_reg_data_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/rd_rs1_addr_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/rd_rs2_addr_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wfi_req
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/mret_req
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/is_fence_i
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/branch_taken
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/branch_target
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/branch_inst_type
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/branch_req
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/branch_predict_success
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/push_ras
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/pop_ras
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/mul_div_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/mul_div_func3
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/result_mul_div
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/mul_div_valid
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/access_csr_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/csr_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/rd_csr_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wr_csr_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/illegal_inst_csr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/inst_addr_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/inst_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wr_reg_en_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wr_reg_addr_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wr_reg_data_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wr_reg_selected_data_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/rd_dtcm_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/dtcm_sel
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/bus_sel
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/inst_addr_wb
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/inst_wb
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/bootrom_inst
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/itcm_inst
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/bootrom_sel
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/itcm_sel
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/branch_jump_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/branch_jump_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/trap_jump
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/trap_jump_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/priv_mode
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/load_use_flag
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/mem_access_ready
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/mul_div_ready
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/inst_addr_if
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/inst_addr_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/inst_addr_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/inst_addr_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/exception_code_if
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/exception_code_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/exception_code_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/exception_code_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/exception_val_if
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/exception_val_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/exception_val_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/exception_val_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/pc_stall
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/ctrl_jump_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/ctrl_jump_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/if_id_stall
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/if_id_flush
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/id_ex_stall
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/id_ex_flush
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/ex_mem_stall
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/ex_mem_flush
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/mem_wb_stall
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/mem_wb_flush
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/exception_inst_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/exception_trap
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/exception_code
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/exception_val
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/next_inst_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/priority_if
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/priority_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/priority_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/priority_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/min_priority
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/sel_stage
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/rd_rs1_addr_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/rd_rs2_addr_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/access_en_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/access_wr_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/wr_reg_en_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/rd_rs1_addr_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/rd_rs2_addr_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/wr_reg_addr_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/wr_reg_en_wb
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/wr_reg_addr_wb
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/alu_op1_from_id_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/alu_op2_from_id_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/rd_rs2_data_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/wr_reg_en_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/wr_reg_addr_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/wr_reg_data_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/wr_reg_data_wb
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/bus_sel
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/bus_done
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/mem_access_ready
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/load_use_flag
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/alu_op1_o
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/alu_op2_o
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/wr_mem_data_temp
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/rd_mem_en_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/forward_A_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/forward_A_wb
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/forward_B_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/forward_B_wb
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/inst_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/inst
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/imm
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/predict_taken
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/predict_target
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/rd_csr_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/illegal_inst_csr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/alu_op1
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/alu_op2
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/jump_imm
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/inst_addr_plus_4
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/wr_mem_data_temp
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/mul_div_valid
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/result_mul_div
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/branch_jump_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/branch_jump_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/exception_code
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/exception_val
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/mul_div_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/mul_div_func3
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/mem_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/wr_mem_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/wr_mem_mask
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/rd_mem_func3
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/wr_reg_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/wr_reg_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/wr_csr_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/wfi_req
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/mret_req
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/is_fence_i
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/branch_taken
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/branch_target
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/branch_inst_type
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/branch_req
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/branch_predict_success
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/push_ras
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/pop_ras
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/opcode
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/rd
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/func3
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/zimm
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/func7
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/equal
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/less_signed
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/less_unsigned
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/sr_shift
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/sr_shift_mask
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/rd_link
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/rs1_link
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/rs1_eq_rd
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Mem_Access/clk
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Mem_Access/rst_n
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Mem_Access/access_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Mem_Access/access_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Mem_Access/access_wr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Mem_Access/bus_tran_done
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Mem_Access/rd_dtcm_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Mem_Access/rd_bus_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Mem_Access/rd_mem_func3
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Mem_Access/wr_reg_data_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Mem_Access/dtcm_sel
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Mem_Access/bus_sel
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Mem_Access/mem_access_ready
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Mem_Access/exception_code
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Mem_Access/exception_val
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Mem_Access/wr_reg_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Mem_Access/rd_mem_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Mem_Access/access_illegal
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Mem_Access/dtcm_sel_d
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Mem_Access/bus_sel_hold
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Mem_Access/access_wr_d
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Mem_Access/access_addr_lsb_d
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Mem_Access/rd_mem_func3_d
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Mem_Access/dtcm_sel_vld
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Mem_Access/bus_sel_vld
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/clk
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/rst_n
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/is_fence_i
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/stall
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/pc
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/branch_pc
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/branch_taken
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/branch_target
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/branch_req
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/branch_predict_success
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/branch_inst_type
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/push_ras
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/pop_ras
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/predict_taken
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/predict_target
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/pc_hash
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/spec_global_history
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/real_global_history
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/spec_global_history_next
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/spec_ras_ptr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/real_ras_ptr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/spec_ras_ptr_next
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/predict_btb_idx
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/predict_pht_idx
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/predict_2bit_cnt
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/predict_pht_taken
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/predict_btb_hit
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/update_btb_idx
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/update_pht_idx
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/update_pc_hash
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/ghr_pht_update_en_latched
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/ghr_update_value_latched
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/pht_update_idx_latched
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/pht_update_taken_latched
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/predict_ras_target
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/predict_btb_target
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/btb_update_en_latched
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/btb_update_idx_latched
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/btb_update_tag_latched
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/btb_update_target_latched
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/btb_update_type_latched
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/btb_update_pop_ras_latched
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/btb_update_push_ras_latched
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/ras_update_en_latched
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/ras_push_latched
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/ras_pop_latched
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/ras_update_ptr_latched
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/ras_update_data_latched
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/ras_latch_ptr_next
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/spec_outcome_en_latched
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/spec_outcome_mispred_latched
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/spec_outcome_taken_latched
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/clk
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/rst_n
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_awid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_awaddr
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_awlen
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_awsize
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_awburst
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_awlock
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_awcache
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_awprot
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_awqos
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_awregion
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_awvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_awready
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_wdata
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_wstrb
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_wlast
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_wvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_wready
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_bid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_bresp
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_bvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_bready
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_arid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_araddr
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_arlen
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_arsize
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_arburst
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_arlock
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_arcache
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_arprot
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_arqos
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_arregion
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_arvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_arready
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_rid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_rdata
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_rresp
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_rlast
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_rvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/s_rready
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_awid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_awaddr
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_awlen
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_awsize
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_awburst
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_awlock
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_awcache
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_awprot
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_awqos
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_awregion
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_awvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_awready
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_wdata
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_wstrb
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_wlast
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_wvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_wready
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_bid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_bresp
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_bvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_bready
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_arid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_araddr
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_arlen
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_arsize
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_arburst
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_arlock
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_arcache
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_arprot
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_arqos
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_arregion
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_arvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_arready
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_rid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_rdata
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_rresp
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_rlast
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_rvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m0_rready
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_awid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_awaddr
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_awlen
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_awsize
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_awburst
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_awlock
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_awcache
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_awprot
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_awqos
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_awregion
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_awvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_awready
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_wdata
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_wstrb
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_wlast
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_wvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_wready
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_bid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_bresp
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_bvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_bready
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_arid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_araddr
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_arlen
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_arsize
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_arburst
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_arlock
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_arcache
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_arprot
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_arqos
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_arregion
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_arvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_arready
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_rid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_rdata
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_rresp
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_rlast
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_rvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m1_rready
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_awid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_awaddr
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_awlen
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_awsize
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_awburst
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_awlock
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_awcache
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_awprot
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_awqos
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_awregion
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_awvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_awready
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_wdata
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_wstrb
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_wlast
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_wvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_wready
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_bid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_bresp
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_bvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_bready
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_arid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_araddr
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_arlen
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_arsize
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_arburst
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_arlock
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_arcache
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_arprot
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_arqos
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_arregion
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_arvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_arready
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_rid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_rdata
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_rresp
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_rlast
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_rvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/m2_rready
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/aw_msb
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/aw_sel_apb
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/aw_sel_mrom_flash
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/aw_sel_ddr
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/ar_msb
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/ar_sel_apb
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/ar_sel_mrom_flash
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/ar_sel_ddr
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/ar_sel_apb_r
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/ar_sel_mrom_flash_r
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/ar_sel_ddr_r
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/aw_sel_apb_r
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/aw_sel_mrom_flash_r
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_Interconnect/aw_sel_ddr_r
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/clk
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/rst_n
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_awid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_awaddr
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_awlen
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_awsize
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_awburst
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_awlock
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_awcache
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_awprot
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_awqos
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_awregion
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_awvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_awready
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_wdata
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_wstrb
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_wlast
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_wvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_wready
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_bid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_bresp
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_bvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_bready
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_arid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_araddr
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_arlen
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_arsize
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_arburst
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_arlock
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_arcache
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_arprot
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_arqos
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_arregion
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_arvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_arready
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_rid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_rdata
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_rresp
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_rlast
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_rvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/s_rready
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/PADDR
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/PSEL
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/PENABLE
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/PWRITE
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/PSTRB
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/PWDATA
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/PRDATA
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/PREADY
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/PSLVERR
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/state
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/next_state
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/apb_transfer
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/apb_write
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/apb_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/apb_wdata
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/apb_wmask
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/apb_rdata
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/apb_tran_done
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/trans_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/trans_error
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/aw_hs
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/w_hs
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/ar_hs
add wave -noupdate /tb_soc_top/u_SoC_top/u_AXI_APB_Bridge/write_req_ready
add wave -noupdate /tb_soc_top/u_SoC_top/u_APB_Interconnect/PADDR
add wave -noupdate /tb_soc_top/u_SoC_top/u_APB_Interconnect/PSEL
add wave -noupdate /tb_soc_top/u_SoC_top/u_APB_Interconnect/i_prdata
add wave -noupdate /tb_soc_top/u_SoC_top/u_APB_Interconnect/i_pready
add wave -noupdate /tb_soc_top/u_SoC_top/u_APB_Interconnect/i_pslverr
add wave -noupdate /tb_soc_top/u_SoC_top/u_APB_Interconnect/o_psel
add wave -noupdate /tb_soc_top/u_SoC_top/u_APB_Interconnect/PRDATA
add wave -noupdate /tb_soc_top/u_SoC_top/u_APB_Interconnect/PREADY
add wave -noupdate /tb_soc_top/u_SoC_top/u_APB_Interconnect/PSLVERR
add wave -noupdate /tb_soc_top/u_SoC_top/u_APB_Interconnect/psel_vec
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/clk
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/rst_n
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/i_transfer
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/i_write
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/i_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/i_wdata
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/i_wmask
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/o_rdata
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/o_tran_done
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/o_awid
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/o_awaddr
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/o_awlen
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/o_awsize
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/o_awburst
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/o_awlock
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/o_awcache
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/o_awprot
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/o_awqos
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/o_awregion
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/o_awvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/i_awready
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/o_wdata
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/o_wstrb
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/o_wlast
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/o_wvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/i_wready
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/i_bid
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/i_bresp
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/i_bvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/o_bready
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/o_arid
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/o_araddr
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/o_arlen
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/o_arsize
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/o_arburst
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/o_arlock
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/o_arcache
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/o_arprot
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/o_arqos
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/o_arregion
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/o_arvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/i_arready
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/i_rid
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/i_rdata
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/i_rresp
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/i_rlast
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/i_rvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/o_rready
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/clk
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/rst_n
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/req_valid
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/req_write
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/req_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/req_wdata
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/req_wstrb
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/req_ready
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/rsp_valid
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/rsp_error
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/rsp_rdata
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_awid
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_awaddr
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_awlen
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_awsize
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_awburst
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_awlock
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_awcache
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_awprot
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_awqos
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_awregion
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_awvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_awready
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_wdata
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_wstrb
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_wlast
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_wvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_wready
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_bid
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_bresp
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_bvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_bready
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_arid
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_araddr
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_arlen
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_arsize
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_arburst
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_arlock
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_arcache
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_arprot
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_arqos
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_arregion
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_arvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_arready
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_rid
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_rdata
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_rresp
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_rlast
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_rvalid
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/m_rready
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/state
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/next_state
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/rsp_valid_d
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/rsp_error_d
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/rsp_rdata_d
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/addr_reg
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/wdata_reg
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/wstrb_reg
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/aw_done
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/w_done
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/take_req
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/launch_wr_now
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/launch_rd_now
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/aw_hs
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/w_hs
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/ar_hs
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/b_hs
add wave -noupdate /tb_soc_top/u_SoC_top/u_Bus_Access/u_AXI_Lite_Master/r_hs
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {198697 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 524
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {171250 ps} {308267 ps}
