onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_soc_top/clk
add wave -noupdate /tb_soc_top/rst_n
add wave -noupdate /tb_soc_top/download_en
add wave -noupdate /tb_soc_top/gpio_io
add wave -noupdate /tb_soc_top/uart_rx
add wave -noupdate /tb_soc_top/uart_tx
add wave -noupdate /tb_soc_top/download_done
add wave -noupdate /tb_soc_top/timer_channel_io
add wave -noupdate /tb_soc_top/prev_pwm
add wave -noupdate /tb_soc_top/period_cnt
add wave -noupdate /tb_soc_top/high_cnt
add wave -noupdate /tb_soc_top/pwm_ch
add wave -noupdate /tb_soc_top/inst_cnt
add wave -noupdate /tb_soc_top/tx_data_valid
add wave -noupdate /tb_soc_top/tx_data_valid_d
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/branch_jump_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/branch_jump_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/trap_jump
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/trap_jump_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/priv_mode
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/load_use_flag
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/mem_access_ready
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/mul_div_ready
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/inst_addr_if
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/inst_addr_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/inst_addr_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/inst_addr_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/exception_code_if
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/exception_code_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/exception_code_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/exception_code_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/exception_val_if
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/exception_val_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/exception_val_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/exception_val_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/bus_sel
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/pc_stall
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/ctrl_jump_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/ctrl_jump_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/if_id_stall
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/if_id_flush
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/id_ex_stall
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/id_ex_flush
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/ex_mem_stall
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/ex_mem_flush
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/mem_wb_stall
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/mem_wb_flush
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/exception_inst_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/exception_trap
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/exception_code
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/exception_val
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/next_inst_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/priority_if
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/priority_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/priority_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/priority_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/min_priority
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/sel_stage
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Pipeline_Ctrl/stall
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/access_en_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/access_wr_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/rd_rs1_addr_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/rd_rs2_addr_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/access_en_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/access_wr_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/wr_reg_en_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/rd_rs1_addr_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/rd_rs2_addr_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/wr_reg_addr_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/access_en_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/access_wr_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/wr_reg_en_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/wr_reg_addr_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/wr_reg_en_wb
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/wr_reg_addr_wb
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/alu_op1_from_id_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/alu_op2_from_id_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/rd_rs2_data_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/wr_reg_data_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/wr_reg_data_wb
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/bus_sel
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/bus_done
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/mem_addr_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/forward_A
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/forward_B
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/forward_C
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/load_use_flag
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/alu_op1_o
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/alu_op2_o
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/wr_mem_data_temp
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/wr_mem_en_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/rd_mem_en_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/wr_mem_en_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/rd_mem_en_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/bus_sel_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Data_Hazard_Forward/wr_mem_data_from_rs2
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/inst_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/inst
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/imm
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/predict_taken
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/predict_target
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/rd_csr_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/illegal_inst_csr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/alu_op1
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/alu_op2
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/wr_mem_data_temp
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/mul_div_valid
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/result_mul_div
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/wr_reg_data_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/wr_reg_data_wb
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/branch_jump_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/branch_jump_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/exception_code
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/exception_val
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/mul_div_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/mul_div_func3
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/mem_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/wr_mem_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/wr_mem_mask
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/rd_mem_func3
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/wr_reg_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/wr_reg_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/wr_csr_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/wfi_req
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/mret_req
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/is_fence_i
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/branch_taken
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/branch_target
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/branch_inst_type
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/branch_req
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/branch_predict_success
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/push_ras
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/pop_ras
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/opcode
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/rd
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/func3
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/zimm
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/func7
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/equal
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/less_signed
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/less_unsigned
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/jump_imm
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/sr_shift
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/sr_shift_mask
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/rd_link
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/rs1_link
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/rs1_eq_rd
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Executer/inst_addr_plus_4
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/clk
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/rst_n
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/download_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/uart_rec_byte
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/uart_rx_valid
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/itcm_wr_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/itcm_wr_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/itcm_wr_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/download_done
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/current_state
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/next_state
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/byte_cnt
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/recv_data_q
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/recv_data_n
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/itcm_addr_access_valid
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/detect_start_frame
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/detect_end_frame
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/word_ready
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/uart_rx_valid_d
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_uart/u_uart_download/uart_rx_valid_pos
add wave -noupdate {/tb_soc_top/u_SoC_top/u_apb_timer/channel_gen[0]/timer_ic_oc_inst/clk}
add wave -noupdate {/tb_soc_top/u_SoC_top/u_apb_timer/channel_gen[0]/timer_ic_oc_inst/rst_n}
add wave -noupdate {/tb_soc_top/u_SoC_top/u_apb_timer/channel_gen[0]/timer_ic_oc_inst/ext_in}
add wave -noupdate {/tb_soc_top/u_SoC_top/u_apb_timer/channel_gen[0]/timer_ic_oc_inst/ext_out}
add wave -noupdate {/tb_soc_top/u_SoC_top/u_apb_timer/channel_gen[0]/timer_ic_oc_inst/ext_dir}
add wave -noupdate {/tb_soc_top/u_SoC_top/u_apb_timer/channel_gen[0]/timer_ic_oc_inst/timer_cnt}
add wave -noupdate {/tb_soc_top/u_SoC_top/u_apb_timer/channel_gen[0]/timer_ic_oc_inst/timer_dir_sel}
add wave -noupdate {/tb_soc_top/u_SoC_top/u_apb_timer/channel_gen[0]/timer_ic_oc_inst/timer_en}
add wave -noupdate {/tb_soc_top/u_SoC_top/u_apb_timer/channel_gen[0]/timer_ic_oc_inst/timer_expired}
add wave -noupdate {/tb_soc_top/u_SoC_top/u_apb_timer/channel_gen[0]/timer_ic_oc_inst/ic_oc_mode}
add wave -noupdate {/tb_soc_top/u_SoC_top/u_apb_timer/channel_gen[0]/timer_ic_oc_inst/filter_mode}
add wave -noupdate {/tb_soc_top/u_SoC_top/u_apb_timer/channel_gen[0]/timer_ic_oc_inst/ic_oc_en}
add wave -noupdate {/tb_soc_top/u_SoC_top/u_apb_timer/channel_gen[0]/timer_ic_oc_inst/polarity}
add wave -noupdate {/tb_soc_top/u_SoC_top/u_apb_timer/channel_gen[0]/timer_ic_oc_inst/trigger_mode}
add wave -noupdate {/tb_soc_top/u_SoC_top/u_apb_timer/channel_gen[0]/timer_ic_oc_inst/cmp_value}
add wave -noupdate {/tb_soc_top/u_SoC_top/u_apb_timer/channel_gen[0]/timer_ic_oc_inst/cap_value}
add wave -noupdate {/tb_soc_top/u_SoC_top/u_apb_timer/channel_gen[0]/timer_ic_oc_inst/ic_oc_irq}
add wave -noupdate {/tb_soc_top/u_SoC_top/u_apb_timer/channel_gen[0]/timer_ic_oc_inst/ext_in_dly}
add wave -noupdate {/tb_soc_top/u_SoC_top/u_apb_timer/channel_gen[0]/timer_ic_oc_inst/rising_edge}
add wave -noupdate {/tb_soc_top/u_SoC_top/u_apb_timer/channel_gen[0]/timer_ic_oc_inst/falling_edge}
add wave -noupdate {/tb_soc_top/u_SoC_top/u_apb_timer/channel_gen[0]/timer_ic_oc_inst/valid_edge}
add wave -noupdate {/tb_soc_top/u_SoC_top/u_apb_timer/channel_gen[0]/timer_ic_oc_inst/ic_state}
add wave -noupdate {/tb_soc_top/u_SoC_top/u_apb_timer/channel_gen[0]/timer_ic_oc_inst/captured_value}
add wave -noupdate {/tb_soc_top/u_SoC_top/u_apb_timer/channel_gen[0]/timer_ic_oc_inst/captured_edge}
add wave -noupdate {/tb_soc_top/u_SoC_top/u_apb_timer/channel_gen[0]/timer_ic_oc_inst/filter_cnt}
add wave -noupdate {/tb_soc_top/u_SoC_top/u_apb_timer/channel_gen[0]/timer_ic_oc_inst/filter_th_latch}
add wave -noupdate {/tb_soc_top/u_SoC_top/u_apb_timer/channel_gen[0]/timer_ic_oc_inst/filter_done}
add wave -noupdate {/tb_soc_top/u_SoC_top/u_apb_timer/channel_gen[0]/timer_ic_oc_inst/capture_trigger}
add wave -noupdate {/tb_soc_top/u_SoC_top/u_apb_timer/channel_gen[0]/timer_ic_oc_inst/capture_trigger_d}
add wave -noupdate {/tb_soc_top/u_SoC_top/u_apb_timer/channel_gen[0]/timer_ic_oc_inst/cmp_match}
add wave -noupdate {/tb_soc_top/u_SoC_top/u_apb_timer/channel_gen[0]/timer_ic_oc_inst/cmp_output}
add wave -noupdate {/tb_soc_top/u_SoC_top/u_apb_timer/channel_gen[0]/timer_ic_oc_inst/cmp_output_d}
add wave -noupdate {/tb_soc_top/u_SoC_top/u_apb_timer/channel_gen[0]/timer_ic_oc_inst/cmp_reg}
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/basic_timer_inst/clk
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/basic_timer_inst/rst_n
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/basic_timer_inst/prescale
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/basic_timer_inst/autoload
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/basic_timer_inst/timer_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/basic_timer_inst/timer_clr
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/basic_timer_inst/timer_dir
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/basic_timer_inst/cnt_wr_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/basic_timer_inst/cnt_wr_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/basic_timer_inst/cnt_rd_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/basic_timer_inst/timer_expired
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/basic_timer_inst/timer_expired_req
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/basic_timer_inst/prescale_cnt
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/basic_timer_inst/prescale_shadow
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/basic_timer_inst/prescale_match
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/basic_timer_inst/timer_cnt
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/basic_timer_inst/timer_cnt_match
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/basic_timer_inst/timer_expired_d
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/PCLK
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/PRESETn
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/PADDR
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/PSEL
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/PENABLE
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/PWRITE
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/PSTRB
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/PWDATA
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/PRDATA
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/PREADY
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/PSLVERR
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/irq_o
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/channel_io
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/channel_i
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/channel_o
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/channel_oe
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/reg_sel
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/timer_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/timer_clr
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/timer_dir_sel
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/timer_prescaler
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/timer_arr
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/timer_cnt
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/timer_int_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/timer_of_int_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/timer_ic_oc_int_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/timer_int_of_pend
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/timer_int_trigger_pend
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/timer_ic_oc_mode
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/timer_filter_mode
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/timer_ic_oc_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/timer_ic_oc_polarity
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/timer_trigger_mode
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/timer_expired
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/timer_expired_req
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/cnt_wr_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/cnt_wr_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/channel_ic_oc_irq
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/timer_ccr_cmp
add wave -noupdate /tb_soc_top/u_SoC_top/u_apb_timer/timer_ccr_cap
add wave -noupdate /tb_soc_top/u_SoC_top/u_CLINT/PCLK
add wave -noupdate /tb_soc_top/u_SoC_top/u_CLINT/PRESETn
add wave -noupdate /tb_soc_top/u_SoC_top/u_CLINT/PADDR
add wave -noupdate /tb_soc_top/u_SoC_top/u_CLINT/PSEL
add wave -noupdate /tb_soc_top/u_SoC_top/u_CLINT/PENABLE
add wave -noupdate /tb_soc_top/u_SoC_top/u_CLINT/PWRITE
add wave -noupdate /tb_soc_top/u_SoC_top/u_CLINT/PSTRB
add wave -noupdate /tb_soc_top/u_SoC_top/u_CLINT/PWDATA
add wave -noupdate /tb_soc_top/u_SoC_top/u_CLINT/PRDATA
add wave -noupdate /tb_soc_top/u_SoC_top/u_CLINT/PREADY
add wave -noupdate /tb_soc_top/u_SoC_top/u_CLINT/PSLVERR
add wave -noupdate /tb_soc_top/u_SoC_top/u_CLINT/mtime_shadow
add wave -noupdate /tb_soc_top/u_SoC_top/u_CLINT/software_int
add wave -noupdate /tb_soc_top/u_SoC_top/u_CLINT/timer_int
add wave -noupdate /tb_soc_top/u_SoC_top/u_CLINT/mtime
add wave -noupdate /tb_soc_top/u_SoC_top/u_CLINT/mtimecmp
add wave -noupdate /tb_soc_top/u_SoC_top/u_CLINT/msip
add wave -noupdate /tb_soc_top/u_SoC_top/sys_clk
add wave -noupdate /tb_soc_top/u_SoC_top/rst_n
add wave -noupdate /tb_soc_top/u_SoC_top/uart_rx
add wave -noupdate /tb_soc_top/u_SoC_top/uart_tx
add wave -noupdate /tb_soc_top/u_SoC_top/gpio_io
add wave -noupdate /tb_soc_top/u_SoC_top/timer_channel_io
add wave -noupdate /tb_soc_top/u_SoC_top/sys_rst_n
add wave -noupdate /tb_soc_top/u_SoC_top/itcm_wr_en
add wave -noupdate /tb_soc_top/u_SoC_top/itcm_wr_addr
add wave -noupdate /tb_soc_top/u_SoC_top/itcm_wr_data
add wave -noupdate /tb_soc_top/u_SoC_top/plic_sel
add wave -noupdate /tb_soc_top/u_SoC_top/bus_transfer
add wave -noupdate /tb_soc_top/u_SoC_top/access_addr
add wave -noupdate /tb_soc_top/u_SoC_top/access_wr
add wave -noupdate /tb_soc_top/u_SoC_top/access_wr_data
add wave -noupdate /tb_soc_top/u_SoC_top/access_wr_mask
add wave -noupdate /tb_soc_top/u_SoC_top/mtime_shadow
add wave -noupdate /tb_soc_top/u_SoC_top/software_int
add wave -noupdate /tb_soc_top/u_SoC_top/timer_int
add wave -noupdate /tb_soc_top/u_SoC_top/external_int
add wave -noupdate /tb_soc_top/u_SoC_top/bus_rdata
add wave -noupdate /tb_soc_top/u_SoC_top/bus_tran_done
add wave -noupdate /tb_soc_top/u_SoC_top/periph_addr
add wave -noupdate /tb_soc_top/u_SoC_top/periph_enable
add wave -noupdate /tb_soc_top/u_SoC_top/periph_write
add wave -noupdate /tb_soc_top/u_SoC_top/periph_wmask
add wave -noupdate /tb_soc_top/u_SoC_top/periph_wdata
add wave -noupdate /tb_soc_top/u_SoC_top/clint_psel
add wave -noupdate /tb_soc_top/u_SoC_top/clint_rdata
add wave -noupdate /tb_soc_top/u_SoC_top/clint_ready
add wave -noupdate /tb_soc_top/u_SoC_top/clint_err
add wave -noupdate /tb_soc_top/u_SoC_top/uart_psel
add wave -noupdate /tb_soc_top/u_SoC_top/uart_rdata
add wave -noupdate /tb_soc_top/u_SoC_top/uart_ready
add wave -noupdate /tb_soc_top/u_SoC_top/uart_err
add wave -noupdate /tb_soc_top/u_SoC_top/uart_irq
add wave -noupdate /tb_soc_top/u_SoC_top/gpio_psel
add wave -noupdate /tb_soc_top/u_SoC_top/gpio_rdata
add wave -noupdate /tb_soc_top/u_SoC_top/gpio_ready
add wave -noupdate /tb_soc_top/u_SoC_top/gpio_err
add wave -noupdate /tb_soc_top/u_SoC_top/gpio_irq
add wave -noupdate /tb_soc_top/u_SoC_top/timer_psel
add wave -noupdate /tb_soc_top/u_SoC_top/timer_rdata
add wave -noupdate /tb_soc_top/u_SoC_top/timer_ready
add wave -noupdate /tb_soc_top/u_SoC_top/timer_err
add wave -noupdate /tb_soc_top/u_SoC_top/timer_irq
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/clk
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/rst_n
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/itcm_wr_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/itcm_wr_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/itcm_wr_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/mtime_shadow
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/software_int
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/timer_int
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/external_int
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/plic_sel
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/bus_rdata
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/bus_tran_done
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/bus_transfer
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/access_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/access_wr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/access_wr_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/access_wr_mask
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/branch_jump_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/branch_jump_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/trap_jump
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/trap_jump_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/priv_mode
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/load_use_flag
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/mem_access_ready
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/mul_div_ready
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/exception_code_if
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/exception_code_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/exception_code_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/exception_code_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/exception_val_if
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/exception_val_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/exception_val_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/exception_val_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/pc_stall
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/ctrl_jump_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/ctrl_jump_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/if_id_stall
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/if_id_flush
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/id_ex_stall
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/id_ex_flush
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/ex_mem_stall
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/ex_mem_flush
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/mem_wb_stall
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/mem_wb_flush
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/exception_inst_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/exception_trap
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/exception_code
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/exception_val
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/next_inst_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/forward_A
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/forward_B
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/forward_C
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/alu_op1_from_id_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/alu_op2_from_id_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/alu_op1_forward
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/alu_op2_forward
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wr_mem_data_temp
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/rs2_data_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wr_reg_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/rd_rs1_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/rd_rs2_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/rd_rs1_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/rd_rs2_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wr_reg_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wr_reg_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/pc
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/inst
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/predict_taken_if
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/predict_target_if
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/inst_addr_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/inst_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/predict_taken_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/predict_target_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/alu_op1_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/alu_op2_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/imm_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/access_en_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/access_wr_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wr_reg_en_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/access_csr_en_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/csr_addr_id
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/inst_addr_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/inst_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/predict_taken_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/predict_target_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/imm_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/access_en_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/access_wr_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/mem_addr_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/rd_mem_func3_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wr_mem_data_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wr_mem_mask_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wr_reg_en_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wr_reg_addr_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wr_reg_data_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/rd_rs1_addr_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/rd_rs2_addr_ex
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wfi_req
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/mret_req
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/is_fence_i
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/branch_taken
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/branch_target
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/branch_inst_type
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/branch_req
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/branch_predict_success
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/push_ras
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/pop_ras
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/mul_div_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/mul_div_func3
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/result_mul_div
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/mul_div_valid
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/access_csr_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/csr_addr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/rd_csr_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wr_csr_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/illegal_inst_csr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/inst_addr_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/inst_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wr_reg_en_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wr_reg_addr_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wr_reg_data_from_ex_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wr_reg_data_mem
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/access_en
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/rd_dtcm_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/rd_plic_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/rd_mem_func3
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wr_mem_data
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/wr_mem_mask
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/dtcm_sel
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/bus_sel
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/inst_addr_wb
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/inst_wb
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/clk
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/rst_n
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/is_fence_i
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/stall
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/pc
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/branch_pc
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/branch_taken
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/branch_target
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/branch_req
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/branch_predict_success
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/branch_inst_type
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/push_ras
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/pop_ras
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/predict_taken
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/predict_target
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/pc_hash
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/spec_global_history
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/real_global_history
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/spec_global_history_next
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/real_global_history_next
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/spec_ras_ptr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/real_ras_ptr
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/spec_ras_ptr_next
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/real_ras_ptr_next
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/ras_full
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/ras_empty
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/predict_btb_idx
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/predict_pht_idx
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/predict_2bit_cnt
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/predict_pht_taken
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/predict_btb_hit
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/update_btb_idx
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/update_pht_idx
add wave -noupdate /tb_soc_top/u_SoC_top/u_RISC_V_Core/u_Dynamic_Branch_Predictor/update_pc_hash
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {19703015904 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 524
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {19702814049 ps} {19703134970 ps}
